language: java

jdk:
  - openjdk14

services:
  - docker

# env:
#   global:
#     secure: DOCKER_USER
#     secure: DOCKER_PASS
#     secure: IMAGE_NAME
#     secure: TEAMS_CHANNEL_URL



notifications:

webhooks: https://outlook.office.com/webhook/fda6319a-169c-47c0-82da-282252ae0fe6@56334c91-7dfb-429e-a42f-d8d72d736139/TravisCI/7931db2c7ac249c5b14dff9813e10338/5aef3a55-a548-44bd-8847-1e840f04a861