server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgres://fuamcipslbugir:841a022cef6ac3afb6a8babcf0f9fbc0bc4c2ccefe121bdffe1736cf16434f0e@ec2-52-31-94-195.eu-west-1.compute.amazonaws.com:5432/d7to3tasuvl5uf
    username: fuamcipslbugir
    password: 841a022cef6ac3afb6a8babcf0f9fbc0bc4c2ccefe121bdffe1736cf16434f0e
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    clean-disabled: false
    clean-on-validation-error: false
    locations: classpath:db/migration
    table: flyway_schema_history