server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sgiextranet
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    clean-disabled: false
    clean-on-validation-error: false
    locations: classpath:db/migration
    table: flyway_schema_history