server:
  port: 8081

spring:
  datasource:
    url: {JDBC_STAGING_DB_URL}
    username: {JDBC_STAGING_DB_USER}
    password: {JDBC_STAGING_DB_PASS}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    clean-disabled: false
    clean-on-validation-error: false
    locations: classpath:db/migration
    table: flyway_schema_history