package com.sgi.extranet.enums;

public enum UserType {
    SIMPATIZANTE, MEMBRO, LIDER_DE_GRUPO, VICE_LIDER_DE_GRUPO, LIDER_DE_DISTRITO,
    VICE_LIDER_DE_DISTRITO, LIDER_DE_CAPITULO, VICE_LIDER_DE_CAPITULO
}
